export const genreList = [
    { title: 'Hip-Hop', value: 'HIP_HOP_RAP', transformedUrl: 'hip-hop-rap' },
    { title: 'Rock', value: 'ROCK', transformedUrl: 'rock' },
    { title: 'House', value: 'HOUSE', transformedUrl: 'house' },
    { title: 'Pop', value: 'POP', transformedUrl: 'pop' },
    { title: 'Country', value: 'COUNTRY', transformedUrl: 'country' },
    { title: 'Alternative', value: 'ALTERNATIVE', transformedUrl: 'alternative' },
    { title: 'K-Pop', value: 'K_POP', transformedUrl: 'k-pop' },
    { title: 'Dance', value: 'DANCE', transformedUrl: 'dance' },
    { title: 'Electronic', value: 'ELECTRONIC', transformedUrl: 'electronic' },
    { title: 'Soul', value: 'SOUL_RNB', transformedUrl: 'soul-rnb' },
    { title: 'Latin', value: 'LATIN', transformedUrl: 'latin' },
    { title: 'Film', value: 'FILM_TV', transformedUrl: 'film-tv' },
    { title: 'Worldwide', value: 'WORLDWIDE', transformedUrl: 'world-wide' },
    { title: 'Reggae', value: 'REGGAE_DANCE_HALL', transformedUrl: 'reggae-dance-hall' },
  ];