export const genreList = [
    { title: 'Hip-Hop', value: 'HIP_HOP_RAP' },
    { title: 'Rock', value: 'ROCK' },
    { title: 'House', value: 'HOUSE' },
    { title: 'Pop', value: 'POP' },
    { title: 'Country', value: 'COUNTRY' },
    { title: 'Alternative', value: 'ALTERNATIVE' },
    { title: 'K-Pop', value: 'K_POP' },
    { title: 'Dance', value: 'DANCE' },
    { title: 'Electronic', value: 'ELECTRONIC' },
    { title: 'Soul', value: 'SOUL_RNB' },
    { title: 'Latin', value: 'LATIN' },
    { title: 'Film', value: 'FILM_TV' },
    { title: 'Worldwide', value: 'WORLDWIDE' },
    { title: 'Reggae', value: 'REGGAE_DANCE_HALL' },
  ];